package com.tian.sleep;

public enum DisplayStatus {
	
	SCREEN_HOME,
	
	SCREEN_INTRO,
	
	SCREEN_CONSENT,
	
	SCREEN_PSQI,
	SCREEN_PSQI_QUESTION,
	
	
	SCREEN_RESULT,
	UPDATE_RESULT_MOVE,
	
	SCREEN_MONITOR,
	UPDATE_MONITOR_SECOND,
	UPDATE_MONITOR_TICK,
	
	SCREEN_RESULT_EVENT,
	SCREEN_RESULT_EVENT_SNORE,
	SCREEN_RESULT_EVENT_COUGH,
	SCREEN_RESULT_EVENT_GETUP,
	SCREEN_RESULT_EVENT_MOVE,
	UPDATE_EVENTRESULT_MOVE,
	
	SCREEN_HISTORY,
	UPDATE_HISTORY_WEEK,
	UPDATE_HISTORY_MONTH,
	UPDATE_HISTORY_YEAR,
	
	SCREEN_HISTORY_QUALITY,
	UPDATE_HISTORY_QUALITY_WEEK,
	UPDATE_HISTORY_QUALITY_MONTH,
	UPDATE_HISTORY_QUALITY_YEAR,
	UPDATE_HISTORY_QUALITY_MOVE,
	
	//SCREEN_HISTORY_EVENT,
	SCREEN_HISTORY_EVENT,
	UPDATE_HISTORY_EVENT_WEEK,
	UPDATE_HISTORY_EVENT_MONTH,
	UPDATE_HISTORY_EVENT_YEAR,
	UPDATE_HISTORY_EVENT_MOVE,
	
	SCREEN_SETTING,
	SCREEN_ABOUT
	

	
	
}
